Repository decide-part-chullo/decide, pull requests merged in 2022-01, with the labels that each got.

#73 Feature/65 entrar app credenciales GitHub y Discord
  decide/authentication/templates/master.html
  decide/authentication/tests.py
  decide/decide/settings.py
  decide/decide/urls.py
  requirements.txt
Labels: new feature

#83 Feature/76 reorganizar credenciales email y apis
  decide/decide/settings.py
  requirements.txt
Labels: change request

#44 Feature/12 inscripcion grupo publico
  decide/authentication/templates/master.html
  decide/authentication/views.py
  decide/census/serializers.py
  decide/census/static/census/style.css
  decide/census/templates/groupList.html
  decide/census/urls.py
  decide/census/views.py
  decide/test-scripts/mixnet
  decide/test-scripts/mixnet/__init__.py
  decide/test-scripts/mixnet/admin.py
  decide/test-scripts/mixnet/apps.py
  decide/test-scripts/mixnet/migrations/0001_initial.py
  decide/test-scripts/mixnet/migrations/0002_auto_20180216_1617.py
  decide/test-scripts/mixnet/migrations/0003_mixnet_auth_position.py
  decide/test-scripts/mixnet/migrations/0004_auto_20180605_0842.py
  decide/test-scripts/mixnet/migrations/__init__.py
  decide/test-scripts/mixnet/mixcrypt.py
  decide/test-scripts/mixnet/models.py
  decide/test-scripts/mixnet/serializers.py
  decide/test-scripts/mixnet/tests.py
  decide/test-scripts/mixnet/urls.py
  decide/test-scripts/mixnet/views.py
  decide/voting/views.py
Labels: new feature

#53 Feature/5 enviar solicitud grupo privado
  decide/base/migrations/0001_initial.py
  decide/census/migrations/0001_initial.py
  decide/census/templates/groupList.html
  decide/census/tests.py
  decide/census/views.py
  decide/mixnet/migrations/0001_initial.py
  decide/store/migrations/0001_initial.py
  decide/test-scripts/mixnet/migrations/0001_initial.py
  decide/test-scripts/mixnet/migrations/0002_auto_20180216_1617.py
  decide/test-scripts/mixnet/migrations/0003_mixnet_auth_position.py
  decide/test-scripts/mixnet/migrations/0004_auto_20180605_0842.py
  decide/voting/migrations/0001_initial.py
Labels: new feature

#45 Feature/32 Votaciones realizadas y pendientes
  decide/authentication/static/booth/style.css
  decide/authentication/static/crypto/bigint.js
  decide/authentication/static/crypto/elgamal.js
  decide/authentication/static/crypto/jsbn.js
  decide/authentication/static/crypto/jsbn2.js
  decide/authentication/static/crypto/sjcl.js
  decide/authentication/templates/master.html
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/booth/urls.py
  decide/census/templates/view_voting.html
  decide/census/urls.py
  decide/census/views.py
  decide/visualizer/urls.py
Labels: new feature

#109 "#108": Añade los tests que habían desaparecido
  decide/census/tests.py
Labels: bug, low
